--liquibase formatted sql
--changeset admin:initial_schema splitStatements:true endDelimiter:;
--preconditions onFail:HALT onError:HALT

CREATE TABLE public.admins (
   id bigint NOT NULL
);

CREATE TABLE public.advertisements (
    id bigint NOT NULL
);

CREATE TABLE public.base_users (
    enable boolean NOT NULL,
    id bigint NOT NULL,
    password_id bigint NOT NULL,
    email character varying(255) NOT NULL,
    role character varying(255),
    CONSTRAINT base_users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);


ALTER TABLE public.base_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.base_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.categories (
    id bigint NOT NULL,
    parent_id bigint,
    name character varying(255)
);

CREATE TABLE public.categories_children (
    category_id bigint NOT NULL,
    children_id bigint NOT NULL
);

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.images (
   id bigint NOT NULL,
   image_urls character varying(2048)[]
);

ALTER TABLE public.images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.orders (
   enable boolean NOT NULL,
   price integer NOT NULL,
   category_id bigint NOT NULL,
   created_at timestamp(6) without time zone,
   id bigint NOT NULL,
   images_id bigint,
   users_id bigint,
   description character varying(255),
   location character varying(255),
   title character varying(255)
);

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.passwords (
  id bigint NOT NULL,
  password character varying(255)
);

ALTER TABLE public.passwords ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.passwords_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.reviews (
    rating integer NOT NULL,
    author_id bigint,
    id bigint NOT NULL,
    target_user_id bigint,
    review_text character varying(255)
);

ALTER TABLE public.reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public."task-workers" (
    tasks_id bigint NOT NULL,
    users_id bigint NOT NULL
);

CREATE TABLE public.tasks (
  accepted_worker_id bigint,
  id bigint NOT NULL
);

CREATE TABLE public.user_favourites (
    orders_id bigint NOT NULL,
    users_id bigint NOT NULL
);

CREATE TABLE public.users (
  rating integer NOT NULL,
  id bigint NOT NULL,
  images_id bigint,
  contacts character varying(255),
  fio character varying(255)
);
