--liquibase formatted sql
--changeset admin:initial_schema splitStatements:true endDelimiter:;
--preconditions onFail:HALT onError:HALT

CREATE TABLE public.admins (
   id bigint NOT NULL
);

CREATE TABLE public.advertisements (
    id bigint NOT NULL
);

CREATE TABLE public.base_users (
    enable boolean NOT NULL,
    id bigint NOT NULL,
    password_id bigint NOT NULL,
    email character varying(255) NOT NULL,
    role character varying(255),
    CONSTRAINT base_users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);


ALTER TABLE public.base_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.base_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.categories (
    id bigint NOT NULL,
    parent_id bigint,
    name character varying(255)
);

CREATE TABLE public.categories_children (
    category_id bigint NOT NULL,
    children_id bigint NOT NULL
);

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.images (
   id bigint NOT NULL,
   image_urls character varying(2048)[]
);

ALTER TABLE public.images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.orders (
   enable boolean NOT NULL,
   price integer NOT NULL,
   category_id bigint NOT NULL,
   created_at timestamp(6) without time zone,
   id bigint NOT NULL,
   images_id bigint,
   users_id bigint,
   description character varying(255),
   location character varying(255),
   title character varying(255)
);

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.passwords (
  id bigint NOT NULL,
  password character varying(255)
);

ALTER TABLE public.passwords ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.passwords_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.reviews (
    rating integer NOT NULL,
    author_id bigint,
    id bigint NOT NULL,
    target_user_id bigint,
    review_text character varying(255)
);

ALTER TABLE public.reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public."task-workers" (
    tasks_id bigint NOT NULL,
    users_id bigint NOT NULL
);

CREATE TABLE public.tasks (
  accepted_worker_id bigint,
  id bigint NOT NULL
);

CREATE TABLE public.user_favourites (
    orders_id bigint NOT NULL,
    users_id bigint NOT NULL
);

CREATE TABLE public.users (
  rating integer NOT NULL,
  id bigint NOT NULL,
  images_id bigint,
  contacts character varying(255),
  fio character varying(255)
);

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT admins_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.advertisements
    ADD CONSTRAINT advertisements_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.base_users
    ADD CONSTRAINT base_users_email_key UNIQUE (email);

ALTER TABLE ONLY public.base_users
    ADD CONSTRAINT base_users_password_id_key UNIQUE (password_id);

ALTER TABLE ONLY public.base_users
    ADD CONSTRAINT base_users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.images
    ADD CONSTRAINT images_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.passwords
    ADD CONSTRAINT passwords_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT fk2rlgtdmsf9rkv0ij8eepy2fbf FOREIGN KEY (id) REFERENCES public.orders(id);

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk4w0qnfg1gsjox5tc0my7cflt FOREIGN KEY (category_id) REFERENCES public.categories(id);

ALTER TABLE ONLY public."task-workers"
    ADD CONSTRAINT fk6nbtxkh285t8wv70fdmxl313g FOREIGN KEY (users_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk985r60nn9fo3ycyuj9pia6ytk FOREIGN KEY (images_id) REFERENCES public.images(id);

ALTER TABLE ONLY public.user_favourites
    ADD CONSTRAINT fk9jxyt42pgti5wapjllcmtjqen FOREIGN KEY (users_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.categories_children
    ADD CONSTRAINT fkcwiwyla89s18q8xxu1dk7mr97 FOREIGN KEY (category_id) REFERENCES public.categories(id);

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fke6k45xxoin4fylnwg2jkehwjf FOREIGN KEY (users_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.user_favourites
    ADD CONSTRAINT fkfpbep3bcstv6e93eogyimtluj FOREIGN KEY (orders_id) REFERENCES public.advertisements(id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkhm4r73yqc8ftjjypiblihknbw FOREIGN KEY (images_id) REFERENCES public.images(id);

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fki1sktfpjrk7gqmcshcinv3m0j FOREIGN KEY (target_user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.advertisements
    ADD CONSTRAINT fkkvtrg2swmwfvm9eu7q3tjack FOREIGN KEY (id) REFERENCES public.orders(id);

ALTER TABLE ONLY public."task-workers"
    ADD CONSTRAINT fklj9o2nn92bps63f0vdhl4plq9 FOREIGN KEY (tasks_id) REFERENCES public.tasks(id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fklnov3in92uyrqb15vfl6s8gb0 FOREIGN KEY (id) REFERENCES public.base_users(id);

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT fkn2b0t8jvsha86dfe3lgudqp4e FOREIGN KEY (accepted_worker_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT fkne80gbu06b6q9xpw1bcbymxgv FOREIGN KEY (id) REFERENCES public.base_users(id);

ALTER TABLE ONLY public.base_users
    ADD CONSTRAINT fkpyc0h4su0pqoilmjghs7f8iif FOREIGN KEY (password_id) REFERENCES public.passwords(id);

ALTER TABLE ONLY public.categories_children
    ADD CONSTRAINT fks5er396t9r98ethqjy3v4v4c7 FOREIGN KEY (children_id) REFERENCES public.categories(id);

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT fksaok720gsu4u2wrgbk10b5n8d FOREIGN KEY (parent_id) REFERENCES public.categories(id);
